# Generated by Django 4.1 on 2022-08-05 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budgetFieldId',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='value',
        ),
        migrations.AddField(
            model_name='budget',
            name='field_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='budget',
            name='field_value',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='budget',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BudgetFields',
        ),
    ]
