# Generated by Django 4.1 on 2022-08-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_budgetfieldid_remove_budget_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='field_name',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='field_value',
            field=models.TextField(default='null'),
        ),
    ]
