# Generated by Django 4.1 on 2022-08-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budgetbyyears_budgetbymonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetbyyears',
            name='field_name',
            field=models.TextField(default='null'),
        ),
    ]
