# Generated by Django 4.1 on 2022-08-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_budgetbyyears_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetbymonths',
            name='field_value',
            field=models.BigIntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='budgetbyyears',
            name='field_value',
            field=models.BigIntegerField(default='null'),
        ),
    ]
