# Generated by Django 4.1 on 2022-08-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_budgetbymonths_field_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='field_value',
            field=models.BigIntegerField(default='null'),
        ),
    ]
